### ISSUE TITLE
Doesn't send your quote

### ISSUE THREAD

**Issue by timotius10** [nirewen/Citador#115] opened 2019-06-19 20:03 UTC
When you click on quote, it quotes. You see it coming up, i type my message, hit send and it's only my message that's sending. The quoted message doesn't send

**Comment by CthulhuOnIce** [comment] 2019-06-19 20:04
Can confirm, broke with new discord update.

**Comment by CthulhuOnIce** [comment] 2019-06-19 20:05
@nirewen is this project still active?

**Comment by TheGameratorT** [comment] 2019-06-20 10:38
Same here

**Comment by CompletelyUnbelievable** [comment] 2019-06-21 04:20
Feel free to try pull #116 and see if that solves your issue.

**Comment by timotius10** [comment] 2019-06-21 09:39
Thanks, i tried it. Opened discord and it says
Just to make sure i did it right; i replaced the text in red with the text
marked in green and save it?
[image: image.png]

**Comment by CompletelyUnbelievable** [comment] 2019-06-21 11:06
You don't need to manually make the changes, you can go to my fork of his repository and get the plugin there. Though I did remember how to make a direct download link using [BD's github download url](https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/CompletelyUnbelievable/Citador/master/Citador.plugin.js).

**Comment by timotius10** [comment] 2019-06-21 11:13
Thanks, this worked. Thank you very much!

**Comment by TheGameratorT** [comment] 2019-06-21 12:49
This fix is very weird, it is not embed :/

**Comment by zaneneuschuler** [comment] 2019-06-22 00:22
@CompletelyUnbelievable Plugin is still broken when attempting to quote an image across guilds, btw.

**Comment by CompletelyUnbelievable** [comment] 2019-06-22 04:16
@zaneneuschuler I don't recall how or if Citador handled citing uploaded images. I'll look around to see if I can find any indication of how/if Citador was handling that. I also just noticed that the guild icons in the settings panel return undefined, so I'll try looking into that. The guild icons in the settings menu returning undefined might be breaking embeded quotes for now.

**Comment by rikusen0335** [comment] 2019-07-01 13:23
Re-install is worked for me. Just delete `Citador.plugin.js` and make sure to install a new one from release.

**Comment by rikusen0335** [comment] 2019-07-01 13:25
Oh, sorry I missed PR has been merged x(

**Comment by KaKi87** [comment] 2019-07-08 20:50
Please upgrade version number when there's update otherwise PluginRepo doesn't know that there's an update available.
Thanks

**Comment by rikusen0335** [comment] 2019-07-09 10:01
I'd like to notice that auto update is not working perfectly.

**Comment by CompletelyUnbelievable** [comment] 2019-07-16 08:10
I tried to mention the version bump thing to him back on July 4th, I stopped worrying about it since it's not really a big deal and I plan to send another pull request somewhere down the line. I just finished making a new plugin that I've been wanting to make for a while, so I will be getting back to working on the version of Citador on the Beta branch of my fork.

**Comment by SventraPopizz** [comment] 2019-08-18 01:16
Latest discord update
![lhcf0y](https://user-images.githubusercontent.com/30782292/63218904-9872dc00-c166-11e9-97d4-d070362b4e7d.png)

**Comment by BuIlDaLiBlE** [comment] 2019-12-08 10:13
So yeah. This happened again.

**Comment by Arion-Kun** [comment] 2019-12-08 15:42
Can Confirm with BullDaLiBlE

**Comment by shinji257** [comment] 2019-12-08 20:47
Confirmed and no amount of massaging the plugin seems to get it to work again.  When you click the quote button it shows up above the message box but when you type your message and press enter it just sends what you typed.  It doesn't send the quote at all.

**Comment by rikusen0335** [comment] 2019-12-09 07:39
Okay guys, I found a solution for only now.
Copy [this code](https://raw.githubusercontent.com/nirewen/Citador/master/Citador.plugin.js), and paste into your `Citador.plugin.js`. Ctrl + A and then Backspace, and Ctrl + V is recommended.

**Comment by KaKi87** [comment] 2019-12-09 08:12
You could simply say : update the plugin.
`Ctrl + S` is even simpler.

**Comment by Arion-Kun** [comment] 2019-12-09 08:52
Both of the lines of code for the plugin are identical. Also btw, the code hasnt been updated in 3 months so its not rly a fix, its just linking to the same code.

**Comment by Marsonge** [comment] 2019-12-10 20:22
Shouldn't this issue be closed and re-opened to make it clear the problem was fixed, then appeared again? 
Reproduced for quite some time now.

**Comment by Arion-Kun** [comment] 2019-12-10 21:10
> Shouldn't this issue be closed and re-opened to make it clear the problem was fixed, then appeared again?
> Reproduced for quite some time now.

Thanks for volunteering!

**Comment by Konohana-Sakuya** [comment] 2019-12-10 21:19
The issue as far as I can tell is that Discord used to use a `<textarea>` element to hold user entry, as evidenced by the jQuery selector `$('.channelTextArea-1LDbYG textarea').val()` at [line 287](https://github.com/nirewen/Citador/blob/0cad457208c88463ffca9426bd041ab71f89f758/Citador.plugin.js#L287), but now uses some convoluted library Slate to do it now, whose documentation I can't be arsed to piece out. As a crude hack there's `$('.channelTextArea-1LDbYG').find('[data-slate-string]').html()` to get the raw contents of the text box, but there might be some unintended side effects to get the text out that way rather than through Slate's intended channels.

**Comment by Marsonge** [comment] 2019-12-10 21:54
> there might be some unintended side effects to get the text out that way rather than through Slate's intended channels.
Yeah, it has a few that I've found: can't send a quote without typing text, adds a <br> tag after your text, and seems to strip away most of your text when using markdowns (\*text\* writes only \*, for example). 
I'm going to read Slate's doc, if I find something useful I'll make a PR!

**Comment by Marsonge** [comment] 2019-12-10 22:13
I did make it work properly using `$('.channelTextArea-1LDbYG').find('[data-slate-string]').text()` instead of `.html()`. This has one downside compared to when Citador was working previously: It doesn't empty your textarea when you send your message with the quote. Otherwise, it works like a charm (can send quoteblock with no message, with \*markup\*, etc). There seems to be no obvious way to empty the slate editor "properly", so only hacks come to mind. Anyone else has an idea?
FYI: Probably worth it to fix on [line 384](https://github.com/nirewen/Citador/blob/0cad457208c88463ffca9426bd041ab71f89f758/Citador.plugin.js#L384) too

**Comment by Marsonge** [comment] 2019-12-11 14:09
Fixed by #133

**Closed** 2019-12-11 14:16 UTC
