### ISSUE TITLE
1.7.2 Not allowing cross channel/cross server quoting

### ISSUE THREAD

**Issue by cetraben** [nirewen/Citador#59] opened 2018-03-11 15:41 UTC
Hello,

When I update from 1.7.1 to 1.7.2 I am no longer able to quote across different channels or servers. Is this intended functionality or a bug?

I have reverted back to 1.7.1 as this is a core piece of functionality for myself.

**Comment by nirewen** [comment] 2018-03-14 02:43
Duplicate of #55 
Use Zere's fork instead (the link is in README btw)
In the next version this won't be an issue anymore

**Closed by nirewen** 2018-03-14 02:43 UTC
